#!/usr/bin/env bash
# check_drive_drop.sh
# Checks Google Drive via rclone for daily curated findings generated by Gemini Gembots.
# If found, copies the directory to the local drop zone and sets SKIP_SCRIPTS=true.
# Otherwise, sets SKIP_SCRIPTS=false.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# Determine dates
TODAY="$(date '+%Y-%m-%d')"
LOG_FILE="$WORKSPACE_DIR/check-drive-drop.log"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"; }

log "=== Pre-flight Google Drive Drop Check start ==="

# Set directories depending on environment
if [[ "${GITHUB_ACTIONS:-}" == "true" ]]; then
    # In GitHub Actions
    GDRIVE_KNOWLEDGE_DIR="/tmp/GDrive-Knowledge"
    # Ensure config file exists from environment secret
    if [[ -n "${RCLONE_CONFIG:-}" ]]; then
        log "Writing RCLONE_CONFIG secret to config file..."
        mkdir -p "$HOME/.config/rclone"
        echo "$RCLONE_CONFIG" > "$HOME/.config/rclone/rclone.conf"
    fi
else
    # Running locally
    GDRIVE_KNOWLEDGE_DIR="$HOME/My Drive/Stack Watch/knowledge-base"
fi

# Initialize skip scripts variable as false
SKIP_SCRIPTS="false"

# Check if rclone is configured and can pull
if command -v rclone &>/dev/null; then
    if rclone listremotes 2>/dev/null | grep -q "^gdrive:$"; then
        log "Rclone gdrive remote found. Syncing today's knowledge-base folder from Google Drive..."
        
        # Check if the folder for today exists on the remote gdrive before copying
        # This is faster than a full sync of the entire remote.
        if rclone lsf gdrive:"Stack Watch/knowledge-base/$TODAY" &>/dev/null; then
            log "Found today's folder ($TODAY) in Google Drive! Copying..."
            mkdir -p "$GDRIVE_KNOWLEDGE_DIR/$TODAY"
            rclone copy gdrive:"Stack Watch/knowledge-base/$TODAY" "$GDRIVE_KNOWLEDGE_DIR/$TODAY"
        else
            log "No folder for today ($TODAY) found in Google Drive."
        fi
    else
        log "Rclone found but 'gdrive' remote is not configured."
    fi
else
    log "Rclone not found. Skipping Google Drive download."
fi

# Now check if the folder exists in the local GDrive knowledge base directory
DRIVE_TODAY_DIR="$GDRIVE_KNOWLEDGE_DIR/$TODAY"
DROP_ZONE_DIR="$WORKSPACE_DIR/$TODAY"

if [[ -d "$DRIVE_TODAY_DIR" && -f "$DRIVE_TODAY_DIR/summary.md" && -f "$DRIVE_TODAY_DIR/REPORT.md" ]]; then
    log "Gemini Gem curated findings detected for today ($TODAY) in Google Drive!"
    
    # Prepare drop zone (clear if exists)
    if [[ -d "$DROP_ZONE_DIR" ]]; then
        log "Cleaning up existing local drop zone directory $DROP_ZONE_DIR"
        rm -rf "$DROP_ZONE_DIR"
    fi
    
    # Copy from Google Drive sync to local drop zone
    log "Copying $DRIVE_TODAY_DIR to $DROP_ZONE_DIR"
    cp -R "$DRIVE_TODAY_DIR" "$DROP_ZONE_DIR"
    
    SKIP_SCRIPTS="true"
    log "Dual-mode status: Gemini Gems curation found. Skipping automated feed collector and screening."
else
    log "No Gemini Gem curated findings detected for today ($TODAY). Automated poller/screening will run."
fi

# Write variable to GITHUB_ENV if running in GHA
if [[ "${GITHUB_ACTIONS:-}" == "true" ]]; then
    echo "SKIP_SCRIPTS=$SKIP_SCRIPTS" >> "$GITHUB_ENV"
    log "Wrote SKIP_SCRIPTS=$SKIP_SCRIPTS to GITHUB_ENV."
else
    log "Dual-mode status (local check): SKIP_SCRIPTS=$SKIP_SCRIPTS"
fi

log "=== Pre-flight Google Drive Drop Check end ==="
